### ISSUE TITLE
add Burp Logger++ support for authenticated connections to elasticsearch

### ISSUE THREAD

**Issue by kbroughton** [kbroughton/BurpSuiteLoggerPlusPlus#1]
Currently Logger++ UI only accepts host and port and thus the ES cluster must be unauthenticated.  Add optional username and password fields to the UI and pass them
to the connection.

**Comment by kbroughton** [comment]
To set up for development I would recommend the following:

Install burp community edition. Install the Logger++ plugin.
Set up foxyproxy or follow instructions on burp website to install a browser plugin to direct traffic to burp. Capture a few requests.

First test that connecting to a local unauthenticated elasticsearch works. I like to use docker-compose and the plugin only supports Elasticsearch < 7.0. I use 6.8. You could put the following in docker-compose.yml and run `docker-compose up` and test http://localhost:9200 and 5601

```
version: '2'
 services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
```
Once that is working, I recommend odfe-docker for running authenticated docker. The default logins are admin/admin and several others found in documentation.
https://opendistro.github.io/for-elasticsearch-docs/docs/install/docker/

Install Intellij or any IDE with remote debugging. Note, most paid IDEs only offer remote debugging in their professional versions. You could get a free trial license to Intellij Pro. Set a breakpoint in the authentication process.

Once all the setup is done, it should be a fairly simple task to add the authentication. I plan to support maintenance for several other burp plugins.
